"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { getSupabase } from "@/lib/supabase-browser";

type Post={id:string;title:string;excerpt:string|null;body:string;status:string;created_at:string;cover_image_url:string|null;video_url:string|null;tags:string[];seo_title:string|null;seo_description:string|null;calculator_name:string|null;calculator_url:string|null;linkedin_copy:string|null;scheduled_at:string|null};
const LINKEDIN_COMPANY="https://www.linkedin.com/company/10945024";
const W_SECTION="https://wsection.linkoteq.com/";
function esc(s:string){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]||c));}
function md(src:string){let x=esc(src);x=x.replace(/```([\s\S]*?)```/g,"<pre><code>$1</code></pre>");x=x.replace(/\$\$([\s\S]*?)\$\$/g,"<div class=\"formulaBlock\">$1</div>");x=x.replace(/^### (.*)$/gm,"<h3>$1</h3>").replace(/^## (.*)$/gm,"<h2>$1</h2>").replace(/^# (.*)$/gm,"<h1>$1</h1>");x=x.replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>").replace(/\*(.*?)\*/g,"<em>$1</em>");x=x.replace(/`([^`]+)`/g,"<code>$1</code>");x=x.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noreferrer">$1</a>');x=x.replace(/!\[([^\]]*)\]\((https?:\/\/[^)]+)\)/g,'<img src="$2" alt="$1" />');x=x.replace(/^> (.*)$/gm,"<blockquote>$1</blockquote>");x=x.replace(/^---$/gm,"<hr />");x=x.replace(/^(?:- .*(?:\n|$))+/gm,m=>"<ul>"+m.trim().split("\n").map(v=>`<li>${v.slice(2)}</li>`).join("")+"</ul>");x=x.replace(/^(?:\d+\. .*(?:\n|$))+/gm,m=>"<ol>"+m.trim().split("\n").map(v=>`<li>${v.replace(/^\d+\. /,"")}</li>`).join("")+"</ol>");x=x.split(/\n{2,}/).map(p=>/^<(h\d|ul|ol|pre|blockquote|hr|div)/.test(p)?p:`<p>${p.replace(/\n/g,"<br />")}</p>`).join("");return x;}
export default function BlogDashboard(){
 const router=useRouter(); const bodyRef=useRef<HTMLTextAreaElement>(null);
 const [posts,setPosts]=useState<Post[]>([]),[editingId,setEditingId]=useState<string|null>(null),[tab,setTab]=useState<"write"|"preview">("write");
 const [title,setTitle]=useState(""),[excerpt,setExcerpt]=useState(""),[body,setBody]=useState(""),[author,setAuthor]=useState(""),[status,setStatus]=useState("Checking access…");
 const [cover,setCover]=useState(""),[video,setVideo]=useState(""),[tags,setTags]=useState(""),[seoTitle,setSeoTitle]=useState(""),[seoDescription,setSeoDescription]=useState("");
 const [calculatorName,setCalculatorName]=useState("W-Section"),[calculatorUrl,setCalculatorUrl]=useState(W_SECTION),[linkedinCopy,setLinkedinCopy]=useState(""),[scheduledAt,setScheduledAt]=useState("");
 const slug=useMemo(()=>title.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,90),[title]);
 const linkedinDraft=useMemo(()=>`${title||"New engineering article"}\n\n${excerpt||"Practical engineering insight from LinkoTech."}${calculatorUrl?`\n\nTry ${calculatorName}: ${calculatorUrl}`:""}\n\n#StructuralEngineering #EngineeringTechnology #LinkoTech`,[title,excerpt,calculatorName,calculatorUrl]);
 async function load(){const s=getSupabase();if(!s)return setStatus("Supabase is not configured.");const {data:a}=await s.auth.getUser();if(!a.user)return router.replace("/blog/login");setAuthor((a.user.user_metadata?.full_name as string)||a.user.email||"LinkoTech");const {data,error}=await s.from("blog_posts").select("id,title,excerpt,body,status,created_at,cover_image_url,video_url,tags,seo_title,seo_description,calculator_name,calculator_url,linkedin_copy,scheduled_at").order("created_at",{ascending:false});if(error)setStatus(error.message);else{setPosts((data as Post[])||[]);setStatus("");}}
 useEffect(()=>{void load();},[]);
 function reset(){setEditingId(null);setTitle("");setExcerpt("");setBody("");setCover("");setVideo("");setTags("");setSeoTitle("");setSeoDescription("");setCalculatorName("W-Section");setCalculatorUrl(W_SECTION);setLinkedinCopy("");setScheduledAt("");setTab("write");}
 function edit(p:Post){setEditingId(p.id);setTitle(p.title);setExcerpt(p.excerpt||"");setBody(p.body||"");setCover(p.cover_image_url||"");setVideo(p.video_url||"");setTags((p.tags||[]).join(", "));setSeoTitle(p.seo_title||"");setSeoDescription(p.seo_description||"");setCalculatorName(p.calculator_name||"");setCalculatorUrl(p.calculator_url||"");setLinkedinCopy(p.linkedin_copy||"");setScheduledAt(p.scheduled_at?p.scheduled_at.slice(0,16):"");setTab("write");window.scrollTo({top:0,behavior:"smooth"});}
 function insert(before:string,after="",placeholder="text"){const el=bodyRef.current;if(!el)return;const a=el.selectionStart,b=el.selectionEnd,sel=body.slice(a,b)||placeholder;setBody(body.slice(0,a)+before+sel+after+body.slice(b));requestAnimationFrame(()=>{el.focus();el.setSelectionRange(a+before.length,a+before.length+sel.length);});}
 async function save(e:FormEvent,publish:boolean){e.preventDefault();const s=getSupabase();if(!s)return setStatus("Supabase is not configured.");const {data:a}=await s.auth.getUser();if(!a.user)return router.replace("/blog/login");const payload={title:title.trim(),excerpt:excerpt.trim()||null,body:body.trim(),author_id:a.user.id,author_name:author,status:publish?"published":"draft",published_at:publish?new Date().toISOString():null,slug:slug||null,cover_image_url:cover.trim()||null,video_url:video.trim()||null,tags:tags.split(",").map(v=>v.trim()).filter(Boolean),seo_title:seoTitle.trim()||title.trim()||null,seo_description:seoDescription.trim()||excerpt.trim()||null,calculator_name:calculatorName.trim()||null,calculator_url:calculatorUrl.trim()||null,linkedin_copy:(linkedinCopy.trim()||linkedinDraft)||null,scheduled_at:scheduledAt?new Date(scheduledAt).toISOString():null};setStatus(editingId?"Updating…":publish?"Publishing…":"Saving draft…");const q=editingId?s.from("blog_posts").update(payload).eq("id",editingId):s.from("blog_posts").insert(payload);const {error}=await q;if(error)return setStatus(error.message);setStatus(editingId?"Updated.":publish?"Published.":"Draft saved.");reset();await load();}
 async function remove(id:string,title:string){if(!confirm(`Delete “${title}”? This cannot be undone.`))return;const s=getSupabase();if(!s)return;setStatus("Deleting…");const {error}=await s.from("blog_posts").delete().eq("id",id);if(error)return setStatus(error.message);if(editingId===id)reset();setStatus("Deleted.");await load();}
 async function copyLinkedIn(){await navigator.clipboard.writeText(linkedinCopy.trim()||linkedinDraft);setStatus("LinkedIn post copied.");}
 async function logout(){const s=getSupabase();if(s)await s.auth.signOut();router.replace("/blog/login");}
 return <main className="dashboard cmsDashboard">
  <div className="dashboardTop"><a href="/"><Image src="/linkotech-logo.svg" alt="LinkoTech" width={250} height={64} priority /></a><div className="cmsTopActions"><a href="/blog">View Blog</a><a href={LINKEDIN_COMPANY} target="_blank" rel="noreferrer">LinkedIn</a><button onClick={logout} className="navCta">Log out</button></div></div>
  <div className="cmsLayout"><section className="dashboardPanel cmsEditor"><div className="cmsHeading"><div><span className="eyebrow">Employee Workspace · Content Studio</span><h2>{editingId?"Edit article":"Create article"}</h2></div>{editingId&&<button type="button" className="secondaryButton" onClick={reset}>New Article</button>}</div>
   <form className="authForm" onSubmit={e=>save(e,true)}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required /></label><label>Excerpt<input value={excerpt} onChange={e=>setExcerpt(e.target.value)} /></label>
    <div className="editorTabs"><button type="button" className={tab==="write"?"active":""} onClick={()=>setTab("write")}>Write</button><button type="button" className={tab==="preview"?"active":""} onClick={()=>setTab("preview")}>Preview</button></div>
    {tab==="write"?<><div className="editorToolbar"><button type="button" onClick={()=>insert("# ","","Heading")}>H1</button><button type="button" onClick={()=>insert("## ","","Heading")}>H2</button><button type="button" onClick={()=>insert("**","**","bold")}>B</button><button type="button" onClick={()=>insert("*","*","italic")}>I</button><button type="button" onClick={()=>insert("> ","","quote")}>❝</button><button type="button" onClick={()=>insert("- ","","list item")}>• List</button><button type="button" onClick={()=>insert("1. ","","list item")}>1. List</button><button type="button" onClick={()=>insert("`","`","code")}>Code</button><button type="button" onClick={()=>insert("```\n","\n```","code block")}>{"</>"}</button><button type="button" onClick={()=>insert("$$\n","\n$$","E = mc^2")}>∑ Formula</button><button type="button" onClick={()=>insert("[","](https://example.com)","link text")}>🔗 Link</button><button type="button" onClick={()=>insert("![","](https://example.com/image.jpg)","image alt")}>🖼 Image</button><button type="button" onClick={()=>insert("| Column 1 | Column 2 |\n| --- | --- |\n| Value 1 | Value 2 |\n", "", "")}>Table</button><button type="button" onClick={()=>insert("\n---\n","","")}>―</button></div><label>Article body<textarea ref={bodyRef} value={body} onChange={e=>setBody(e.target.value)} required className="markdownEditor" placeholder="Write with the toolbar or Markdown…" /></label></>:<div className="articlePreview">{cover&&<img src={cover} alt="Article cover preview" />}<h1>{title||"Untitled Article"}</h1>{excerpt&&<p className="lead">{excerpt}</p>}<div dangerouslySetInnerHTML={{__html:md(body||"Start writing to preview your article.")}} />{calculatorUrl&&<a className="calculatorCta" href={calculatorUrl} target="_blank" rel="noreferrer">Try {calculatorName||"Calculator"} →</a>}</div>}
    <details open><summary>Media & Assets</summary><div className="cmsTwoCol"><label>Cover image URL<input type="url" value={cover} onChange={e=>setCover(e.target.value)} /></label><label>Video URL<input type="url" value={video} onChange={e=>setVideo(e.target.value)} /></label></div><label>Tags / topics<input value={tags} onChange={e=>setTags(e.target.value)} /></label></details>
    <details><summary>SEO</summary><label>SEO title<input value={seoTitle} onChange={e=>setSeoTitle(e.target.value)} /></label><label>Meta description<textarea value={seoDescription} onChange={e=>setSeoDescription(e.target.value)} /></label><small>Slug: /blog/{slug||"article-slug"}</small></details>
    <details><summary>Calculator Marketing</summary><div className="cmsTwoCol"><label>Tool name<input value={calculatorName} onChange={e=>setCalculatorName(e.target.value)} /></label><label>Tool URL<input type="url" value={calculatorUrl} onChange={e=>setCalculatorUrl(e.target.value)} /></label></div></details>
    <details open><summary>LinkedIn-first Marketing</summary><label>LinkedIn post<textarea value={linkedinCopy} onChange={e=>setLinkedinCopy(e.target.value)} placeholder={linkedinDraft} /></label><div className="cmsButtonRow"><button type="button" onClick={()=>setLinkedinCopy(linkedinDraft)}>Generate LinkedIn Draft</button><button type="button" onClick={copyLinkedIn}>Copy LinkedIn Post</button><a className="navCta" href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Flinkoteq.com%2Fblog" target="_blank" rel="noreferrer">Open LinkedIn Share</a></div></details>
    <label>Schedule (optional)<input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} /></label><div className="cmsButtonRow"><button type="button" onClick={e=>save(e as unknown as FormEvent,false)}>{editingId?"Save Changes":"Save Draft"}</button><button type="submit">{editingId?"Update & Publish":"Publish Post"}</button></div>
   </form>{status&&<div className="authStatus">{status}</div>}</section>
   <aside className="dashboardPanel cmsLibrary"><div className="cmsHeading"><div><span className="eyebrow">Content Library</span><h2>Articles</h2></div><span className="countBadge">{posts.length}</span></div><div className="postList">{posts.map(p=><article className="postRow" key={p.id}><div className="postRowTop"><strong>{p.title}</strong><span className={`statusPill ${p.status}`}>{p.status}</span></div><span>{new Date(p.created_at).toLocaleDateString()}</span><div className="postActions"><button type="button" onClick={()=>edit(p)}>Edit</button><button type="button" className="dangerAction" onClick={()=>remove(p.id,p.title)}>Delete</button></div></article>)}{!posts.length&&<p>No posts yet.</p>}</div></aside>
  </div>
 </main>;
}
