"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { getSupabase } from "@/lib/supabase-browser";
import RichEditor from "./rich-editor";

type Post={id:string;title:string;excerpt:string|null;body:string;status:string;created_at:string;cover_image_url:string|null;video_url:string|null;tags:string[];seo_title:string|null;seo_description:string|null;calculator_name:string|null;calculator_url:string|null;linkedin_copy:string|null;scheduled_at:string|null;slug:string|null};
const LINKEDIN_COMPANY="https://www.linkedin.com/company/10945024";
const W_SECTION="https://wsection.linkoteq.com/";
const DEFAULT_AGENT_PROMPT="Write publication-ready LinkoTech engineering content. Keep the tone technical, credible, concise, and useful to practicing engineers. Structure the article with clear headings, examples, tables where useful, and a practical CTA. Never invent code clauses or test results. Prepare SEO metadata and a LinkedIn-first post for professional engineers and decision makers.";

export default function BlogDashboard(){
 const router=useRouter();
 const [posts,setPosts]=useState<Post[]>([]),[editingId,setEditingId]=useState<string|null>(null),[preview,setPreview]=useState(false),[query,setQuery]=useState("");
 const [title,setTitle]=useState(""),[excerpt,setExcerpt]=useState(""),[body,setBody]=useState("<p></p>"),[author,setAuthor]=useState(""),[status,setStatus]=useState("Checking access…");
 const [cover,setCover]=useState(""),[video,setVideo]=useState(""),[tags,setTags]=useState(""),[seoTitle,setSeoTitle]=useState(""),[seoDescription,setSeoDescription]=useState("");
 const [calculatorName,setCalculatorName]=useState("W-Section"),[calculatorUrl,setCalculatorUrl]=useState(W_SECTION),[linkedinCopy,setLinkedinCopy]=useState(""),[scheduledAt,setScheduledAt]=useState("");
 const [aiOpen,setAiOpen]=useState(false),[aiKey,setAiKey]=useState(""),[aiPrompt,setAiPrompt]=useState(""),[brandPrompt,setBrandPrompt]=useState(DEFAULT_AGENT_PROMPT),[aiBusy,setAiBusy]=useState(false);
 const slug=useMemo(()=>title.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,90),[title]);
 const shareUrl=useMemo(()=>`https://linkoteq.com/blog/${slug||""}`,[slug]);
 const linkedinDraft=useMemo(()=>`${title||"New engineering article"}\n\n${excerpt||"Practical engineering insight from LinkoTech."}${calculatorUrl?`\n\nTry ${calculatorName}: ${calculatorUrl}`:""}\n\n#StructuralEngineering #EngineeringTechnology #LinkoTech`,[title,excerpt,calculatorName,calculatorUrl]);
 const visiblePosts=useMemo(()=>posts.filter(p=>p.title.toLowerCase().includes(query.toLowerCase())),[posts,query]);

 async function load(){const s=getSupabase();if(!s)return setStatus("Supabase is not configured.");const {data:a}=await s.auth.getUser();if(!a.user)return router.replace("/blog/login");setAuthor((a.user.user_metadata?.full_name as string)||a.user.email||"LinkoTech");const {data,error}=await s.from("blog_posts").select("id,title,excerpt,body,status,created_at,cover_image_url,video_url,tags,seo_title,seo_description,calculator_name,calculator_url,linkedin_copy,scheduled_at,slug").order("created_at",{ascending:false});if(error)setStatus(error.message);else{setPosts((data as Post[])||[]);setStatus("");}}
 useEffect(()=>{void load();},[]);
 function reset(){setEditingId(null);setTitle("");setExcerpt("");setBody("<p></p>");setCover("");setVideo("");setTags("");setSeoTitle("");setSeoDescription("");setCalculatorName("W-Section");setCalculatorUrl(W_SECTION);setLinkedinCopy("");setScheduledAt("");setPreview(false);}
 function edit(p:Post){setEditingId(p.id);setTitle(p.title);setExcerpt(p.excerpt||"");setBody(p.body||"<p></p>");setCover(p.cover_image_url||"");setVideo(p.video_url||"");setTags((p.tags||[]).join(", "));setSeoTitle(p.seo_title||"");setSeoDescription(p.seo_description||"");setCalculatorName(p.calculator_name||"");setCalculatorUrl(p.calculator_url||"");setLinkedinCopy(p.linkedin_copy||"");setScheduledAt(p.scheduled_at?p.scheduled_at.slice(0,16):"");setPreview(false);window.scrollTo({top:0,behavior:"smooth"});}
 async function save(e:FormEvent,publish:boolean){e.preventDefault();const s=getSupabase();if(!s)return setStatus("Supabase is not configured.");const {data:a}=await s.auth.getUser();if(!a.user)return router.replace("/blog/login");const payload={title:title.trim(),excerpt:excerpt.trim()||null,body,author_id:a.user.id,author_name:author,status:publish?"published":"draft",published_at:publish?new Date().toISOString():null,slug:slug||null,cover_image_url:cover.trim()||null,video_url:video.trim()||null,tags:tags.split(",").map(v=>v.trim()).filter(Boolean),seo_title:seoTitle.trim()||title.trim()||null,seo_description:seoDescription.trim()||excerpt.trim()||null,calculator_name:calculatorName.trim()||null,calculator_url:calculatorUrl.trim()||null,linkedin_copy:(linkedinCopy.trim()||linkedinDraft)||null,scheduled_at:scheduledAt?new Date(scheduledAt).toISOString():null};setStatus(editingId?"Updating…":publish?"Publishing…":"Saving draft…");const q=editingId?s.from("blog_posts").update(payload).eq("id",editingId):s.from("blog_posts").insert(payload);const {error}=await q;if(error)return setStatus(error.message);setStatus(editingId?"Updated.":publish?"Published.":"Draft saved.");reset();await load();}
 async function remove(id:string,name:string){if(!confirm(`Delete “${name}”? This cannot be undone.`))return;const s=getSupabase();if(!s)return;setStatus("Deleting…");const {error}=await s.from("blog_posts").delete().eq("id",id);if(error)return setStatus(error.message);if(editingId===id)reset();setStatus("Deleted.");await load();}
 async function duplicate(p:Post){const s=getSupabase();if(!s)return;const {data:a}=await s.auth.getUser();if(!a.user)return;const {error}=await s.from("blog_posts").insert({title:`${p.title} (Copy)`,excerpt:p.excerpt,body:p.body,author_id:a.user.id,author_name:author,status:"draft",cover_image_url:p.cover_image_url,video_url:p.video_url,tags:p.tags,seo_title:p.seo_title,seo_description:p.seo_description,calculator_name:p.calculator_name,calculator_url:p.calculator_url,linkedin_copy:p.linkedin_copy});if(error)setStatus(error.message);else{setStatus("Duplicated as draft.");await load();}}
 async function generateAI(){setAiBusy(true);setStatus("AI agent is preparing the article…");try{const r=await fetch("/api/blog-ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:aiPrompt,apiKey:aiKey,brandPrompt,calculator_name:calculatorName,calculator_url:calculatorUrl})});const d=await r.json();if(!r.ok)throw new Error(d.error||"AI generation failed.");setTitle(d.title||title);setExcerpt(d.excerpt||excerpt);setBody(d.body_html||body);setSeoTitle(d.seo_title||"");setSeoDescription(d.seo_description||"");setLinkedinCopy(d.linkedin_copy||"");if(Array.isArray(d.tags))setTags(d.tags.join(", "));setAiOpen(false);setStatus("AI draft loaded into the editor. Review before publishing.");}catch(err){setStatus(err instanceof Error?err.message:"AI generation failed.");}finally{setAiBusy(false);}}
 async function copyLinkedIn(){await navigator.clipboard.writeText(linkedinCopy.trim()||linkedinDraft);setStatus("LinkedIn post copied.");}
 async function logout(){const s=getSupabase();if(s)await s.auth.signOut();router.replace("/blog/login");}
 const enc=encodeURIComponent;

 return <main className="dashboard cmsDashboard">
  <div className="dashboardTop"><a href="/"><Image src="/linkotech-logo.svg" alt="LinkoTech" width={250} height={64} priority /></a><div className="cmsTopActions"><a href="/blog">View Blog</a><a href={LINKEDIN_COMPANY} target="_blank" rel="noreferrer">LinkedIn</a><button onClick={logout} className="navCta">Log out</button></div></div>
  <div className="cmsLayout"><section className="dashboardPanel cmsEditor"><div className="cmsHeading"><div><span className="eyebrow">Employee Workspace · Content Studio</span><h2>{editingId?"Edit Article":"Create Article"}</h2></div><div className="cmsButtonRow"><button type="button" className="aiButton" onClick={()=>setAiOpen(true)}>✨ Generate with AI</button>{editingId&&<button type="button" className="secondaryButton" onClick={reset}>New Article</button>}</div></div>
   <form className="authForm" onSubmit={e=>save(e,true)}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required /></label><label>Excerpt<input value={excerpt} onChange={e=>setExcerpt(e.target.value)} /></label>
    <div className="editorModeBar"><strong>Article</strong><button type="button" className={!preview?"active":""} onClick={()=>setPreview(false)}>Edit</button><button type="button" className={preview?"active":""} onClick={()=>setPreview(true)}>Preview</button></div>
    {!preview?<RichEditor key={editingId||"new"} value={body} onChange={setBody} onStatus={setStatus}/>:<div className="articlePreview">{cover&&<img src={cover} alt="Article cover" />}<h1>{title||"Untitled Article"}</h1>{excerpt&&<p className="lead">{excerpt}</p>}<div className="articleRichBody" dangerouslySetInnerHTML={{__html:body||"<p>Start writing to preview your article.</p>"}} />{calculatorUrl&&<a className="calculatorCta" href={calculatorUrl} target="_blank" rel="noreferrer">Try {calculatorName||"Calculator"} →</a>}</div>}
    <details open><summary>Media & Assets</summary><div className="cmsTwoCol"><label>Cover image URL<input type="url" value={cover} onChange={e=>setCover(e.target.value)} placeholder="Upload inside the editor or paste a cover URL" /></label><label>Video URL<input type="url" value={video} onChange={e=>setVideo(e.target.value)} /></label></div><label>Tags / topics<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="steel, structural engineering, CSA S16" /></label></details>
    <details><summary>SEO</summary><label>SEO title<input value={seoTitle} onChange={e=>setSeoTitle(e.target.value)} /></label><label>Meta description<textarea value={seoDescription} onChange={e=>setSeoDescription(e.target.value)} /></label><small>Slug: /blog/{slug||"article-slug"}</small></details>
    <details><summary>Calculator Marketing</summary><div className="cmsTwoCol"><label>Tool name<input value={calculatorName} onChange={e=>setCalculatorName(e.target.value)} /></label><label>Tool URL<input type="url" value={calculatorUrl} onChange={e=>setCalculatorUrl(e.target.value)} /></label></div><p className="muted">This CTA is included in the article preview and can also be referenced in the LinkedIn draft.</p></details>
    <details open><summary>LinkedIn-first Marketing</summary><label>LinkedIn post<textarea value={linkedinCopy} onChange={e=>setLinkedinCopy(e.target.value)} placeholder={linkedinDraft} /></label><div className="cmsButtonRow"><button type="button" onClick={()=>setLinkedinCopy(linkedinDraft)}>Build LinkedIn Draft</button><button type="button" onClick={copyLinkedIn}>Copy LinkedIn Post</button><a className="navCta" href={`https://www.linkedin.com/sharing/share-offsite/?url=${enc(shareUrl)}`} target="_blank" rel="noreferrer">Share to LinkedIn</a><a className="navCta" href={`https://twitter.com/intent/tweet?url=${enc(shareUrl)}&text=${enc(title||"LinkoTech article")}`} target="_blank" rel="noreferrer">Share to X</a><a className="navCta" href={`https://www.facebook.com/sharer/sharer.php?u=${enc(shareUrl)}`} target="_blank" rel="noreferrer">Share to Facebook</a></div></details>
    <label>Schedule (optional)<input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} /></label><div className="cmsButtonRow"><button type="button" onClick={e=>save(e as unknown as FormEvent,false)}>{editingId?"Save Changes":"Save Draft"}</button><button type="submit">{editingId?"Update & Publish":"Publish Post"}</button></div>
   </form>{status&&<div className="authStatus">{status}</div>}</section>
   <aside className="dashboardPanel cmsLibrary"><div className="cmsHeading"><div><span className="eyebrow">Content Library</span><h2>Articles</h2></div><span className="countBadge">{posts.length}</span></div><input className="cmsSearch" placeholder="Search articles…" value={query} onChange={e=>setQuery(e.target.value)} /><div className="postList">{visiblePosts.map(p=><article className="postRow" key={p.id}><div className="postRowTop"><strong>{p.title}</strong><span className={`statusPill ${p.status}`}>{p.status}</span></div><span>{new Date(p.created_at).toLocaleDateString()}</span><div className="postActions"><button type="button" onClick={()=>edit(p)}>Edit</button>{p.status==="published"&&p.slug&&<a href={`/blog/${p.slug}`} target="_blank">View</a>}<button type="button" onClick={()=>duplicate(p)}>Duplicate</button><button type="button" className="dangerAction" onClick={()=>remove(p.id,p.title)}>Delete</button></div></article>)}{!visiblePosts.length&&<p>No posts found.</p>}</div></aside>
  </div>
  {aiOpen&&<div className="aiModalBackdrop" onClick={()=>!aiBusy&&setAiOpen(false)}><section className="aiModal" onClick={e=>e.stopPropagation()}><div className="cmsHeading"><div><span className="eyebrow">LinkoTech AI Content Agent</span><h2>Generate a Complete Article</h2></div><button type="button" onClick={()=>setAiOpen(false)}>✕</button></div><label>OpenAI API key (optional if OPENAI_API_KEY is configured in Vercel)<input type="password" value={aiKey} onChange={e=>setAiKey(e.target.value)} placeholder="sk-…" autoComplete="off" /></label><label>Agent instructions<textarea value={brandPrompt} onChange={e=>setBrandPrompt(e.target.value)} style={{minHeight:140}} /></label><label>Your prompt<textarea value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} placeholder="Example: Write a technical launch article for the W-Section verification calculator, explain the workflow, benefits, limitations, and include a LinkedIn CTA." style={{minHeight:150}} /></label><p className="muted">The agent returns the article already formatted for this editor, plus SEO metadata, tags and LinkedIn copy. Review it before publishing.</p><div className="cmsButtonRow"><button type="button" disabled={aiBusy||!aiPrompt.trim()} onClick={generateAI}>{aiBusy?"Generating…":"Generate Full Draft"}</button><button type="button" onClick={()=>setAiOpen(false)}>Cancel</button></div></section></div>}
 </main>;
}
