"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { getSupabase } from "@/lib/supabase-browser";
import RichEditor from "./rich-editor";
import MediaPanel from "./media-panel";

type Post={id:string;title:string;excerpt:string|null;body:string;status:string;created_at:string;author_name:string|null;show_author_name:boolean;cover_image_url:string|null;video_url:string|null;cover_image_alt:string|null;cover_image_title:string|null;cover_image_caption:string|null;cover_image_meta:string|null;cover_image_position:string|null;cover_image_size:string|null;video_title:string|null;video_caption:string|null;video_thumbnail_url:string|null;video_meta:string|null;tags:string[];seo_title:string|null;seo_description:string|null;calculator_name:string|null;calculator_url:string|null;linkedin_copy:string|null;scheduled_at:string|null;slug:string|null};
type EditorMode="edit"|"preview"|"html";
const LINKEDIN_COMPANY="https://www.linkedin.com/company/10945024";
const W_SECTION="https://wsection.linkoteq.com/";
const DEFAULT_AGENT_PROMPT="Write publication-ready LinkoTech engineering content. Keep the tone technical, credible, concise, and useful to practicing engineers. Structure the article with clear headings, examples, tables where useful, and a practical CTA. Never invent code clauses or test results. Prepare SEO metadata and a LinkedIn-first post. Plan image and video blocks using the LinkoTech media rules: include accessible alt text, title, caption, social/search description, sensible placement and content-relative sizing. Never invent media URLs; return media briefs and placeholders that the editor can replace with uploaded assets.";
function safe(v:string){return v.replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]||c));}

export default function BlogDashboard(){
 const router=useRouter();
 const [posts,setPosts]=useState<Post[]>([]),[editingId,setEditingId]=useState<string|null>(null),[mode,setMode]=useState<EditorMode>("edit"),[query,setQuery]=useState("");
 const [title,setTitle]=useState(""),[excerpt,setExcerpt]=useState(""),[body,setBody]=useState("<p></p>"),[status,setStatus]=useState("Checking access…");
 const [authorName,setAuthorName]=useState(""),[showAuthorName,setShowAuthorName]=useState(false);
 const [cover,setCover]=useState(""),[video,setVideo]=useState(""),[tags,setTags]=useState(""),[seoTitle,setSeoTitle]=useState(""),[seoDescription,setSeoDescription]=useState("");
 const [imageAlt,setImageAlt]=useState(""),[imageTitle,setImageTitle]=useState(""),[imageCaption,setImageCaption]=useState(""),[imageMeta,setImageMeta]=useState(""),[imagePosition,setImagePosition]=useState("center"),[imageSize,setImageSize]=useState("wide");
 const [videoTitle,setVideoTitle]=useState(""),[videoCaption,setVideoCaption]=useState(""),[videoThumbnail,setVideoThumbnail]=useState(""),[videoMeta,setVideoMeta]=useState("");
 const [calculatorName,setCalculatorName]=useState("W-Section"),[calculatorUrl,setCalculatorUrl]=useState(W_SECTION),[linkedinCopy,setLinkedinCopy]=useState(""),[scheduledAt,setScheduledAt]=useState("");
 const [aiOpen,setAiOpen]=useState(false),[aiKey,setAiKey]=useState(""),[aiPrompt,setAiPrompt]=useState(""),[brandPrompt,setBrandPrompt]=useState(DEFAULT_AGENT_PROMPT),[aiBusy,setAiBusy]=useState(false);
 const slug=useMemo(()=>title.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,90),[title]);
 const linkedinDraft=useMemo(()=>`${title||"New engineering article"}\n\n${excerpt||"Practical engineering insight from LinkoTech."}${calculatorUrl?`\n\nTry ${calculatorName}: ${calculatorUrl}`:""}\n\n#StructuralEngineering #EngineeringTechnology #LinkoTech`,[title,excerpt,calculatorName,calculatorUrl]);
 const visiblePosts=useMemo(()=>posts.filter(p=>p.title.toLowerCase().includes(query.toLowerCase())),[posts,query]);

 async function load(){const s=getSupabase();if(!s)return setStatus("Supabase is not configured.");const {data:a}=await s.auth.getUser();if(!a.user)return router.replace("/blog/login");const {data,error}=await s.from("blog_posts").select("id,title,excerpt,body,status,created_at,author_name,show_author_name,cover_image_url,video_url,cover_image_alt,cover_image_title,cover_image_caption,cover_image_meta,cover_image_position,cover_image_size,video_title,video_caption,video_thumbnail_url,video_meta,tags,seo_title,seo_description,calculator_name,calculator_url,linkedin_copy,scheduled_at,slug").order("created_at",{ascending:false});if(error)setStatus(error.message);else{setPosts((data as Post[])||[]);setStatus("");}}
 useEffect(()=>{void load();},[]);
 function reset(){setEditingId(null);setTitle("");setExcerpt("");setBody("<p></p>");setAuthorName("");setShowAuthorName(false);setCover("");setVideo("");setImageAlt("");setImageTitle("");setImageCaption("");setImageMeta("");setImagePosition("center");setImageSize("wide");setVideoTitle("");setVideoCaption("");setVideoThumbnail("");setVideoMeta("");setTags("");setSeoTitle("");setSeoDescription("");setCalculatorName("W-Section");setCalculatorUrl(W_SECTION);setLinkedinCopy("");setScheduledAt("");setMode("edit");}
 function edit(p:Post){setEditingId(p.id);setTitle(p.title);setExcerpt(p.excerpt||"");setBody(p.body||"<p></p>");setAuthorName(p.author_name||"");setShowAuthorName(Boolean(p.show_author_name));setCover(p.cover_image_url||"");setVideo(p.video_url||"");setImageAlt(p.cover_image_alt||"");setImageTitle(p.cover_image_title||"");setImageCaption(p.cover_image_caption||"");setImageMeta(p.cover_image_meta||"");setImagePosition(p.cover_image_position||"center");setImageSize(p.cover_image_size||"wide");setVideoTitle(p.video_title||"");setVideoCaption(p.video_caption||"");setVideoThumbnail(p.video_thumbnail_url||"");setVideoMeta(p.video_meta||"");setTags((p.tags||[]).join(", "));setSeoTitle(p.seo_title||"");setSeoDescription(p.seo_description||"");setCalculatorName(p.calculator_name||"");setCalculatorUrl(p.calculator_url||"");setLinkedinCopy(p.linkedin_copy||"");setScheduledAt(p.scheduled_at?p.scheduled_at.slice(0,16):"");setMode("edit");window.scrollTo({top:0,behavior:"smooth"});}
 function insertImageBlock(){if(!cover)return;const html=`<figure class="mediaBlock media-${safe(imageSize)} media-${safe(imagePosition)}"><img src="${safe(cover)}" alt="${safe(imageAlt||title||"LinkoTech article image")}" title="${safe(imageTitle)}" />${imageCaption?`<figcaption>${safe(imageCaption)}</figcaption>`:""}</figure><p><br></p>`;setBody(v=>v.replace(/<div class="aiMediaPlaceholder" data-media="image">[\s\S]*?<\/div>/,html)||`${v}${html}`);setStatus("Image block inserted into the article.");}
 function insertVideoBlock(){if(!video)return;const html=`<figure class="mediaBlock videoBlock">${videoThumbnail?`<img src="${safe(videoThumbnail)}" alt="${safe(videoTitle||"Video thumbnail")}" />`:""}<div class="videoLinkCard"><strong>${safe(videoTitle||"Video")}</strong>${videoCaption?`<p>${safe(videoCaption)}</p>`:""}<a href="${safe(video)}" target="_blank" rel="noreferrer">Watch video →</a></div></figure><p><br></p>`;setBody(v=>v.replace(/<div class="aiMediaPlaceholder" data-media="video">[\s\S]*?<\/div>/,html)||`${v}${html}`);setStatus("Video block inserted into the article.");}
 async function save(e:FormEvent,publish:boolean){e.preventDefault();const s=getSupabase();if(!s)return setStatus("Supabase is not configured.");const {data:a}=await s.auth.getUser();if(!a.user)return router.replace("/blog/login");const publishedSlug=slug;const cleanAuthor=authorName.trim();const payload={title:title.trim(),excerpt:excerpt.trim()||null,body,author_id:a.user.id,author_name:cleanAuthor||null,show_author_name:Boolean(showAuthorName&&cleanAuthor),status:publish?"published":"draft",published_at:publish?new Date().toISOString():null,slug:slug||null,cover_image_url:cover.trim()||null,video_url:video.trim()||null,cover_image_alt:imageAlt.trim()||null,cover_image_title:imageTitle.trim()||null,cover_image_caption:imageCaption.trim()||null,cover_image_meta:imageMeta.trim()||null,cover_image_position:imagePosition,cover_image_size:imageSize,video_title:videoTitle.trim()||null,video_caption:videoCaption.trim()||null,video_thumbnail_url:videoThumbnail.trim()||null,video_meta:videoMeta.trim()||null,tags:tags.split(",").map(v=>v.trim()).filter(Boolean),seo_title:seoTitle.trim()||title.trim()||null,seo_description:seoDescription.trim()||excerpt.trim()||null,calculator_name:calculatorName.trim()||null,calculator_url:calculatorUrl.trim()||null,linkedin_copy:(linkedinCopy.trim()||linkedinDraft)||null,scheduled_at:scheduledAt?new Date(scheduledAt).toISOString():null};setStatus(editingId?"Updating…":publish?"Publishing…":"Saving draft…");const q=editingId?s.from("blog_posts").update(payload).eq("id",editingId):s.from("blog_posts").insert(payload);const {error}=await q;if(error)return setStatus(error.message);if(publish&&publishedSlug)setStatus(`Published successfully. Open /blog/${publishedSlug} to view and share the article.`);else setStatus(editingId?"Updated.":"Draft saved.");reset();await load();}
 async function remove(id:string,name:string){if(!confirm(`Delete “${name}”? This cannot be undone.`))return;const s=getSupabase();if(!s)return;setStatus("Deleting…");const {error}=await s.from("blog_posts").delete().eq("id",id);if(error)return setStatus(error.message);if(editingId===id)reset();setStatus("Deleted.");await load();}
 async function duplicate(p:Post){const s=getSupabase();if(!s)return;const {data:a}=await s.auth.getUser();if(!a.user)return;const {error}=await s.from("blog_posts").insert({title:`${p.title} (Copy)`,excerpt:p.excerpt,body:p.body,author_id:a.user.id,author_name:p.author_name,show_author_name:p.show_author_name,status:"draft",cover_image_url:p.cover_image_url,video_url:p.video_url,cover_image_alt:p.cover_image_alt,cover_image_title:p.cover_image_title,cover_image_caption:p.cover_image_caption,cover_image_meta:p.cover_image_meta,cover_image_position:p.cover_image_position,cover_image_size:p.cover_image_size,video_title:p.video_title,video_caption:p.video_caption,video_thumbnail_url:p.video_thumbnail_url,video_meta:p.video_meta,tags:p.tags,seo_title:p.seo_title,seo_description:p.seo_description,calculator_name:p.calculator_name,calculator_url:p.calculator_url,linkedin_copy:p.linkedin_copy});if(error)setStatus(error.message);else{setStatus("Duplicated as draft.");await load();}}
 async function generateAI(){setAiBusy(true);setStatus("AI agent is preparing the article and media plan…");try{const s=getSupabase();const {data:{session}}=await s?.auth.getSession()||{data:{session:null}};const r=await fetch("/api/blog-ai",{method:"POST",headers:{"Content-Type":"application/json",...(session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{})},body:JSON.stringify({prompt:aiPrompt,apiKey:aiKey,brandPrompt,calculator_name:calculatorName,calculator_url:calculatorUrl,image_position:imagePosition,image_size:imageSize})});const d=await r.json();if(!r.ok)throw new Error(d.error||"AI generation failed.");setTitle(d.title||title);setExcerpt(d.excerpt||excerpt);setBody(d.body_html||body);setSeoTitle(d.seo_title||"");setSeoDescription(d.seo_description||"");setLinkedinCopy(d.linkedin_copy||"");if(Array.isArray(d.tags))setTags(d.tags.join(", "));setImageAlt(d.image_alt||"");setImageTitle(d.image_title||"");setImageCaption(d.image_caption||"");setImageMeta(d.image_meta||d.image_brief||"");if(d.image_position)setImagePosition(d.image_position);if(d.image_size)setImageSize(d.image_size);setVideoTitle(d.video_title||"");setVideoCaption(d.video_caption||"");setVideoMeta(d.video_meta||d.video_brief||"");setAiOpen(false);setStatus("AI draft and media plan loaded. Upload/select the actual media, then insert the media blocks before publishing.");}catch(err){setStatus(err instanceof Error?err.message:"AI generation failed.");}finally{setAiBusy(false);}}
 async function copyLinkedIn(){await navigator.clipboard.writeText(linkedinCopy.trim()||linkedinDraft);setStatus("LinkedIn post copied.");}
 async function logout(){const s=getSupabase();if(s)await s.auth.signOut();router.replace("/blog/login");}

 return <main className="dashboard cmsDashboard">
  <div className="dashboardTop"><a href="/"><Image src="/linkotech-logo.svg" alt="LinkoTech" width={250} height={64} priority /></a><div className="cmsTopActions"><a href="/blog">View Blog</a><a href={LINKEDIN_COMPANY} target="_blank" rel="noreferrer">LinkedIn</a><button onClick={logout} className="navCta">Log out</button></div></div>
  <div className="cmsLayout"><section className="dashboardPanel cmsEditor"><div className="cmsHeading"><div><span className="eyebrow">Employee Workspace · Content Studio</span><h2>{editingId?"Edit Article":"Create Article"}</h2></div><div className="cmsButtonRow"><button type="button" className="aiButton" onClick={()=>setAiOpen(true)}>✨ Generate with AI</button>{editingId&&<button type="button" className="secondaryButton" onClick={reset}>New Article</button>}</div></div>
   <form className="authForm" onSubmit={e=>save(e,true)}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required /></label><label>Excerpt<input value={excerpt} onChange={e=>setExcerpt(e.target.value)} /></label>
    <section className="authorSettingsBox"><div><strong>Author</strong><p className="muted">Optional. Leave this off if you want the published article to show only the date.</p></div><label>Author name<input value={authorName} onChange={e=>setAuthorName(e.target.value)} placeholder="Optional author name" /></label><label className="authorVisibilityToggle"><input type="checkbox" checked={showAuthorName} onChange={e=>setShowAuthorName(e.target.checked)} /> <span>Show author name on published article</span></label></section>
    <div className="editorModeBar"><strong>Article</strong><button type="button" className={mode==="edit"?"active":""} onClick={()=>setMode("edit")}>Edit</button><button type="button" className={mode==="preview"?"active":""} onClick={()=>setMode("preview")}>Preview</button><button type="button" className={mode==="html"?"active":""} onClick={()=>setMode("html")}>Advanced HTML</button></div>
    {mode==="edit"&&<RichEditor key={editingId||"new"} value={body} onChange={setBody} onStatus={setStatus}/>} 
    {mode==="html"&&<label className="htmlSourceLabel">HTML source<textarea className="htmlSourceEditor" value={body} onChange={e=>setBody(e.target.value)} spellCheck={false} style={{minHeight:480,fontFamily:"ui-monospace,SFMono-Regular,Menlo,Consolas,monospace",lineHeight:1.6}} /></label>}
    {mode==="preview"&&<div className="articlePreview">{cover&&<figure className={`mediaFigure media-${imageSize} media-${imagePosition}`}><img src={cover} alt={imageAlt||title||"Article cover"} title={imageTitle}/>{imageCaption&&<figcaption>{imageCaption}</figcaption>}</figure>}<div className="articleMeta">{showAuthorName&&authorName.trim()?<>{authorName.trim()} · </>:null}{new Date().toLocaleDateString()}</div><h1>{title||"Untitled Article"}</h1>{excerpt&&<p className="lead">{excerpt}</p>}<div className="articleRichBody" dangerouslySetInnerHTML={{__html:body||"<p>Start writing to preview your article.</p>"}} />{calculatorUrl&&<a className="calculatorCta" href={calculatorUrl} target="_blank" rel="noreferrer">Try {calculatorName||"Calculator"} →</a>}</div>}
    <details open><summary>Media Studio — Image & Video</summary><MediaPanel imageUrl={cover} setImageUrl={setCover} imageAlt={imageAlt} setImageAlt={setImageAlt} imageTitle={imageTitle} setImageTitle={setImageTitle} imageCaption={imageCaption} setImageCaption={setImageCaption} imageMeta={imageMeta} setImageMeta={setImageMeta} imagePosition={imagePosition} setImagePosition={setImagePosition} imageSize={imageSize} setImageSize={setImageSize} videoUrl={video} setVideoUrl={setVideo} videoTitle={videoTitle} setVideoTitle={setVideoTitle} videoCaption={videoCaption} setVideoCaption={setVideoCaption} videoThumbnail={videoThumbnail} setVideoThumbnail={setVideoThumbnail} videoMeta={videoMeta} setVideoMeta={setVideoMeta} onStatus={setStatus} onInsertImage={insertImageBlock} onInsertVideo={insertVideoBlock}/><label>Tags / topics<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="steel, structural engineering, CSA S16" /></label></details>
    <details><summary>SEO</summary><label>SEO title<input value={seoTitle} onChange={e=>setSeoTitle(e.target.value)} /></label><label>Meta description<textarea value={seoDescription} onChange={e=>setSeoDescription(e.target.value)} /></label><small>Slug: /blog/{slug||"article-slug"}</small></details>
    <details><summary>Calculator Marketing</summary><div className="cmsTwoCol"><label>Tool name<input value={calculatorName} onChange={e=>setCalculatorName(e.target.value)} /></label><label>Tool URL<input type="url" value={calculatorUrl} onChange={e=>setCalculatorUrl(e.target.value)} /></label></div><p className="muted">This CTA is included in the article preview and can also be referenced in the LinkedIn draft.</p></details>
    <details open><summary>LinkedIn Marketing Copy</summary><label>LinkedIn post<textarea value={linkedinCopy} onChange={e=>setLinkedinCopy(e.target.value)} placeholder={linkedinDraft} /></label><div className="cmsButtonRow"><button type="button" onClick={()=>setLinkedinCopy(linkedinDraft)}>Build LinkedIn Draft</button><button type="button" onClick={copyLinkedIn}>Copy LinkedIn Post</button></div><p className="muted">Social share buttons appear on the published article after publishing, not inside the writing form.</p></details>
    <label>Schedule (optional)<input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} /></label><div className="cmsButtonRow"><button type="button" onClick={e=>save(e as unknown as FormEvent,false)}>{editingId?"Save Changes":"Save Draft"}</button><button type="submit">{editingId?"Update & Publish":"Publish Post"}</button></div>
   </form>{status&&<div className="authStatus">{status}</div>}</section>
   <aside className="dashboardPanel cmsLibrary"><div className="cmsHeading"><div><span className="eyebrow">Content Library</span><h2>Articles</h2></div><span className="countBadge">{posts.length}</span></div><input className="cmsSearch" placeholder="Search articles…" value={query} onChange={e=>setQuery(e.target.value)} /><div className="postList">{visiblePosts.map(p=><article className="postRow" key={p.id}><div className="postRowTop"><strong>{p.title}</strong><span className={`statusPill ${p.status}`}>{p.status}</span></div><span>{new Date(p.created_at).toLocaleDateString()}</span><div className="postActions"><button type="button" onClick={()=>edit(p)}>Edit</button>{p.status==="published"&&p.slug&&<a href={`/blog/${p.slug}`} target="_blank">View & Share</a>}<button type="button" onClick={()=>duplicate(p)}>Duplicate</button><button type="button" className="dangerAction" onClick={()=>remove(p.id,p.title)}>Delete</button></div></article>)}{!visiblePosts.length&&<p>No posts found.</p>}</div></aside>
  </div>
  {aiOpen&&<div className="aiModalBackdrop" onClick={()=>!aiBusy&&setAiOpen(false)}><section className="aiModal" onClick={e=>e.stopPropagation()}><div className="cmsHeading"><div><span className="eyebrow">LinkoTech AI Content Agent</span><h2>Generate a Complete Article</h2></div><button type="button" onClick={()=>setAiOpen(false)}>✕</button></div><label>OpenAI API key (optional if OPENAI_API_KEY is configured in Vercel)<input type="password" value={aiKey} onChange={e=>setAiKey(e.target.value)} placeholder="sk-…" autoComplete="off" /></label><label>Agent instructions<textarea value={brandPrompt} onChange={e=>setBrandPrompt(e.target.value)} style={{minHeight:170}} /></label><label>Your prompt<textarea value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} placeholder="Example: Write a technical launch article for the W-Section verification calculator. Recommend a professional engineering image, its exact placement, alt text, caption and social metadata, and include a LinkedIn CTA." style={{minHeight:150}} /></label><p className="muted">The agent returns article HTML already matched to this CMS, plus SEO, LinkedIn copy and a structured media plan. It never invents image/video URLs: upload the real asset in Media Studio and use Insert Media Block.</p><div className="cmsButtonRow"><button type="button" disabled={aiBusy||!aiPrompt.trim()} onClick={generateAI}>{aiBusy?"Generating…":"Generate Full Draft"}</button><button type="button" onClick={()=>setAiOpen(false)}>Cancel</button></div></section></div>}
 </main>;
}
