"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { getSupabase } from "@/lib/supabase-browser";

type Article={title:string;excerpt:string|null;body:string;author_name:string|null;show_author_name:boolean;published_at:string|null;created_at:string;cover_image_url:string|null;video_url:string|null;cover_image_alt:string|null;cover_image_title:string|null;cover_image_caption:string|null;cover_image_meta:string|null;cover_image_position:string|null;cover_image_size:string|null;video_title:string|null;video_caption:string|null;video_thumbnail_url:string|null;video_meta:string|null;tags:string[];calculator_name:string|null;calculator_url:string|null;seo_title:string|null;seo_description:string|null};

export default function ArticlePage(){
 const params=useParams<{slug:string}>(); const [article,setArticle]=useState<Article|null>(null); const [status,setStatus]=useState("Loading article…"); const [copied,setCopied]=useState("");
 useEffect(()=>{const s=getSupabase();if(!s)return setStatus("Article service is unavailable.");void s.from("blog_posts").select("title,excerpt,body,author_name,show_author_name,published_at,created_at,cover_image_url,video_url,cover_image_alt,cover_image_title,cover_image_caption,cover_image_meta,cover_image_position,cover_image_size,video_title,video_caption,video_thumbnail_url,video_meta,tags,calculator_name,calculator_url,seo_title,seo_description").eq("slug",params.slug).eq("status","published").single().then(({data,error})=>{if(error||!data)setStatus("Article not found.");else{setArticle(data as Article);setStatus("");document.title=(data.seo_title||data.title)+" | LinkoTech";const meta=document.querySelector('meta[name="description"]');if(meta)meta.setAttribute("content",data.seo_description||data.excerpt||"");}});},[params.slug]);
 if(!article)return <main className="publicArticle"><p>{status}</p></main>;
 const url=typeof window!=="undefined"?window.location.href:"https://linkoteq.com/blog"; const encoded=encodeURIComponent(url); const text=encodeURIComponent(article.title);
 async function copyLink(){await navigator.clipboard.writeText(url);setCopied("Link copied");setTimeout(()=>setCopied(""),1800);}
 async function copyInstagram(){const current=article;if(!current)return;const caption=`${current.title}\n\n${current.excerpt||""}\n\nRead more: ${url}\n\n#LinkoTech #Engineering #StructuralEngineering`;await navigator.clipboard.writeText(caption);setCopied("Instagram caption copied");setTimeout(()=>setCopied(""),1800);}
 return <main className="publicArticle">
  <a className="articleBrand" href="/"><Image src="/linkotech-logo.svg" alt="LinkoTech" width={230} height={58} priority /></a>
  <article className="articleShell">
   {article.cover_image_url&&<figure className={`mediaFigure media-${article.cover_image_size||"wide"} media-${article.cover_image_position||"center"}`}><img src={article.cover_image_url} alt={article.cover_image_alt||article.title} title={article.cover_image_title||undefined}/>{article.cover_image_caption&&<figcaption>{article.cover_image_caption}</figcaption>}{article.cover_image_meta&&<div className="articleMediaMeta">{article.cover_image_meta}</div>}</figure>}
   <div className="articleMeta">{article.show_author_name&&article.author_name?<>{article.author_name} · </>:null}{new Date(article.published_at||article.created_at).toLocaleDateString()}</div><h1>{article.title}</h1>{article.excerpt&&<p className="articleLead">{article.excerpt}</p>}
   <div className="articleRichBody" dangerouslySetInnerHTML={{__html:article.body}} />
   {article.video_url&&<figure className="mediaBlock videoBlock">{article.video_thumbnail_url&&<img src={article.video_thumbnail_url} alt={article.video_title||"Video thumbnail"}/>}<div className="videoLinkCard"><strong>{article.video_title||"Related video"}</strong>{article.video_caption&&<p>{article.video_caption}</p>}<a href={article.video_url} target="_blank" rel="noreferrer">Watch video →</a>{article.video_meta&&<span className="articleMediaMeta">{article.video_meta}</span>}</div></figure>}
   {article.calculator_url&&<section className="articleToolCta"><div><span>Related engineering tool</span><h2>{article.calculator_name||"LinkoTech Calculator"}</h2><p>Continue from the article into the interactive engineering workflow.</p></div><a href={article.calculator_url} target="_blank" rel="noreferrer">Try the Calculator →</a></section>}
   {!!article.tags?.length&&<div className="articleTags">{article.tags.map(t=><span key={t}>#{t}</span>)}</div>}
   <section className="sharePanel"><div className="sharePanelTitle"><strong>Share this article</strong><span>Published content only</span></div><div className="shareButtons"><a className="linkedinShare" href={`https://www.linkedin.com/sharing/share-offsite/?url=${encoded}`} target="_blank" rel="noreferrer">LinkedIn</a><a href={`https://twitter.com/intent/tweet?url=${encoded}&text=${text}`} target="_blank" rel="noreferrer">X</a><a href={`https://t.me/share/url?url=${encoded}&text=${text}`} target="_blank" rel="noreferrer">Telegram</a><a href={`https://www.facebook.com/sharer/sharer.php?u=${encoded}`} target="_blank" rel="noreferrer">Facebook</a><a href={`https://www.reddit.com/submit?url=${encoded}&title=${text}`} target="_blank" rel="noreferrer">Reddit</a><a href={`mailto:?subject=${text}&body=${encoded}`}>Email</a><button type="button" onClick={copyInstagram}>Instagram Caption</button><button type="button" onClick={copyLink}>Copy Link</button></div>{copied&&<div className="shareFeedback">{copied}</div>}</section>
  </article>
 </main>;
}