-- Reserved migration number.
-- No schema change is required for the current labeling workspace UI improvements.
-- Selected drawings are edited before upload; existing candidate records and audit history remain unchanged.
